[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
chain_id = 84532
auto_detect_solc = false
solc_version = "0.8.25"
evm_version = "paris"
via_ir = true
cbor_metadata = true
use_literal_content = false
bytecode_hash = "ipfs"
optimizer = true
optimizer_runs = 200
libraries = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
